[Global]
port=8080
server_origin="123.206.116.244"
level_db_file_path="./wlt.core"
bolaxy_node_url="http://192.168.10.189:8080"
def_host="192.168.9.189"
def_port=8080
def_chain_id="chainId100001"
def_name="默认圈子"
def_desc="一些比较有意思的描述"

[MySQL]
user="root"
pasw="87651234"
prot="tcp"
host="122.51.106.29"
port="3306"
dbnm="wallet"